version: '3.8'

services:

  # REF: https://hub.docker.com/r/arm64v8/telegraf
  telegraf:
    image: arm64v8/telegraf:1.22.4
    hostname: telegraf
    environment:
      - HOST_ETC=/host/etc
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - INFLUX_URL=http://influxdb:8086
    ports:
      # Telegraf unencrypted UDP 8092
      - mode: ingress
        target: 8092
        published: 8092
        protocol: udp
      # Telegraf unencrypted TCP 8094
      - mode: ingress
        target: 8094
        published: 8094
        protocol: tcp
      # Telegraf StatsD unencrypted TCP 8125
      - mode: ingress
        target: 8125
        published: 8125
        protocol: tcp
    networks:
      - tick-stack-net1
    volumes:
      - type: bind
        source: /opt/docker/telegraf/etc/telegraf
        target: /etc/telegraf
      - type: bind
        source: /etc
        target: /host/etc
        read_only: true
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      labels:
        local.description: "Telegraf"
      restart_policy:
        condition: on-failure

  # REF: https://hub.docker.com/r/arm64v8/influxdb
  influxdb:
    image: arm64v8/influxdb:2.2.0-alpine
    hostname: influxdb
    environment:
      INFLUXDB_GRAPHITE_ENABLED: 1
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: influxdb
      DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
      DOCKER_INFLUXDB_INIT_ORG: RadioFan.Club
      DOCKER_INFLUXDB_INIT_BUCKET: db_map
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: influxdb
    ports:
      # InfluxDB Graphite unencrypted TCP 2003
      - mode: ingress
        target: 2003
        published: 2003
        protocol: tcp
      # InfluxDB HTTP API unencrypted TCP 8086
      - mode: ingress
        target: 8086
        published: 8086
        protocol: tcp
    networks:
      - tick-stack-net1
    volumes:
      - type: bind
        source: /opt/docker/influxdb/etc/influxdb
        target: /etc/influxdb
      - type: bind
        source: /opt/docker/influxdb/var/lib/influxdb
        target: /var/lib/influxdb
    deploy:
      labels:
        local.description: "InfluxDB"
      restart_policy:
        condition: on-failure

  # REF: https://hub.docker.com/r/arm64v8/chronograf
  chronograf:
    image: arm64v8/chronograf:1.9.4
    hostname: chronograf
    environment:
      - influxdb-url=http://influxdb:8086
    ports:
      # Chronograf unencrypted TCP 8888
      - mode: ingress
        target: 8888
        published: 8888
        protocol: tcp
    networks:
      - tick-stack-net1
    volumes:
      - type: bind
        source: /opt/docker/chronograf/var/lib/chronograf
        target: /var/lib/chronograf
    deploy:
      labels:
        local.description: "Chronograf"
      restart_policy:
        condition: on-failure

  # REF: https://hub.docker.com/r/arm64v8/kapacitor
  kapacitor:
    image: arm64v8/kapacitor:1.6.4
    hostname: kapacitor
    ports:
      # Kapacitor unencrypted TCP 9092
      - mode: ingress
        target: 9092
        published: 9092
        protocol: tcp
    networks:
      - tick-stack-net1
    volumes:
      - type: bind
        source: /opt/docker/kapacitor/etc/kapacitor
        target: /etc/kapacitor      
      - type: bind
        source: /opt/docker/kapacitor/var/lib/kapacitor
        target: /var/lib/kapacitor
    deploy:
      labels:
        local.description: "Kapacitor"
      restart_policy:
        condition: on-failure

networks:
  tick-stack-net1:
